#!/usr/bin/env ruby
# encoding: UTF-8

if ARGV.size != 5
  puts 'dividend <final|interim> <date_paid> <tax_year_end> <net> <company_year_end>'
  puts '  date_paid yyyymmdd'
  puts '  tax_year_end yyyymmdd'
  puts '  net net dividend actually paid out'
  puts '  company_year_end company accounts year end date (yyyymmdd)'
end

require 'active_support/time'
require 'active_support/core_ext/numeric/conversions'
require 'wicked_pdf'
require 'slim'
require 'ostruct'
require_relative 'base'


class Dividend
  attr_reader :type, :tax_year_end, :shares, :net, :tax_credit, :gross, :amount, :company_year_end

  def initialize args
    @name = 'dividend'
    @type = ARGV[0] == 'final' ? 'Final' : 'Interim'
    @date_paid = Date.parse(ARGV[1])
    @tax_year_end = Date.parse(ARGV[2]).to_s(:long)
    @shares = 100
    @net = ARGV[3].to_f
    @tax_credit = @net * 0.111111
    @gross = @net + @tax_credit
    @amount = @net / @shares
    @company_year_end = Date.parse(ARGV[4]).to_s(:long)
  end

  def date_paid(format = :long)
    @date_paid.to_s(format)
  end

  def name(ext)
    "#{name}.#{ext}"
  end

  def filename
    "#{@name}_#{date_paid(:file)}.pdf"
  end
end

write_pdf(Dividend.new(ARGV))
