#!/usr/bin/env ruby

if ARGV.empty?
  puts <<-END_USAGE
    Generate a timesheet (CSV) and invoice (PDF).

    invoice path [-f] [-p] -n [-x|-i [day[am|pm]],[...]]
      path  - path to the client directory
      -f    - overwrite existing timesheet/invoice
      -n    - generate timesheet/invoice for n months ago (-0 to -12)
      -x    - specify days to exclude (sat/sun excluded anyway)
      -i    - specify days to include
      am|pm - just the morning or afternoon was taken off (half a day)

  END_USAGE
  exit
end

require 'bundler/setup'
require 'active_support'
require 'active_support/time'
require 'active_support/core_ext/numeric/conversions'
require 'prawn'
require 'yaml'
require 'fileutils'

# Arguments (other args must be removed before days)
CLIENT_PATH = ARGV.delete_at(0)
days_are_included = ARGV.delete('-i')
days_are_excluded = ARGV.delete('-x')
if days_are_included && days_are_excluded
  puts 'Days can only be included or excluded. Not both. Specify -i or -x.'
  exit 1
end

I18n.load_path << "#{__dir__}/en.yml"
I18n.t('date.formats').each do |key, value|
  Date::DATE_FORMATS[key] = value
end

def currency(amount)
  format '£%.2f', amount
end

def vat
  subtotal * 0.2
end

def total
  subtotal + vat
end

def invoice_num(date)
  previous_invoice_count = Dir[File.join(CLIENT_PATH, 'invoice_*')].size
  if previous_invoice_count.zero?
    puts 'WARNING: NO PREVIOUS INVOICES DETECTED'
    puts 'If this is the first invoice you can ignore this warning'
    puts 'Otherwise make sure previous invoices are in the correct format:'
    puts "    #{invoice_filename(date)}"
  end
  format '%03d', (previous_invoice_count + 1)
end

def file_date(prefix, date, suffix)
  "#{prefix}_#{date.to_fs(:file_no_day)}.#{suffix}"
end

def timesheet_filename(date)
  file_date('timesheet', date, 'csv')
end

def invoice_filename(date)
  file_date('invoice', date, 'pdf')
end

def working_days(date, days, days_are_included)
  if days_are_included
    days[date.day] || ''
  elsif date.saturday? || date.sunday?
    ''
  else
    1.0 - days[date.day].to_f
  end
end

c = YAML.safe_load(File.open(File.join(__dir__, 'config.yml')))
c = c.merge YAML.safe_load(File.open(File.join(CLIENT_PATH, 'config.yml')))

overwrite = ARGV.delete('-f')
month = (0..12).detect { |n| ARGV.delete("-#{n}") }
days =
  if !ARGV.empty?
    ARGV.first.split(',').map do |day|
      [day.to_i, day =~ /am|pm/ ? 0.5 : 1.0]
    end.to_h
  else
    []
  end

date = month.month.ago.beginning_of_month.to_date

total_days = 0
(date..date.end_of_month.to_date).each do |d|
  day = working_days(d, days, days_are_included)
  total_days += day if day.is_a?(Float)
end

def padded_text text, *args
  pad_bottom(2) do
    text text, *args
  end
end

grey = '999999'

def write_timesheet(date, cfg, days, days_are_included)
  csv = "#{cfg['service']}\n"
  csv += "by #{cfg['account_name']} (#{cfg['company']})\n"
  csv += "for #{date.to_fs(:month_name_year)}\n"
  csv += "#{cfg['client_reference_label']} #{cfg['client_reference']}\n"
  csv += "Generated on: #{Date.today.to_fs(:long)}\n"
  csv += "\n"
  csv += "Day,Hours\n"
  total = 0
  (date..date.end_of_month.to_date).each do |d|
    day = working_days(d, days, days_are_included)
    total += day if day.is_a?(Float)
    csv += "#{d.day},#{day * cfg['hours_per_day']}\n"
  end
  csv += "\n"
  csv += "Total (hours),#{total * cfg['hours_per_day']}\n"
  csv += "Total (days),#{total}\n"
  csv += "\n"
  csv += "\n"
  csv += "\n"

  File.open(File.join(CLIENT_PATH, timesheet_filename(date)), 'w') { |f| f.write csv }
  total
end

invoice_path = File.join(CLIENT_PATH, invoice_filename(date))

if File.exist?(invoice_path)
  if overwrite
    FileUtils.rm_f(invoice_path)
  else
    puts "Existing invoice detected for #{date}"
    puts 'Use -f to overwrite'
    exit 1
  end
end

write_timesheet(date, c, days, days_are_included)

FONT_PATH = '/nix/store/3xh7wz81amv6qcvk9bz62z95dlvpvs14-noto-fonts-24.3.1/share/fonts/noto/NotoSans[wdth,wght].ttf'.freeze
Prawn::Document.generate(invoice_path) do
  font_families.update(
    'FreeSans' => {
      normal: FONT_PATH,
      bold: FONT_PATH
    }
  )

  font 'FreeSans'
  font_size 14

  # ADDRESS
  float do
    font_size(25) { text c['company'].to_s }
    move_down 10
    padded_text "#{c['address1']}, #{c['address2']}, #{c['address3']}"
    padded_text c['email']
    padded_text "Company no. #{c['company_no']}"
    padded_text "VAT no. #{c['vat_no']}"
  end

  font_size(25) do
    text 'INVOICE', color: grey, align: :right
  end
  move_down 30
  pad_bottom(10) do
    text "INVOICE NO: <b>#{c['invoice_prefix']}#{invoice_num(date)}</b>", align: :right, inline_format: true
  end
  text "DATE: <b>#{Date.today.to_fs(:long)}</b>", align: :right, inline_format: true

  move_down 20

  # TO
  move_down 20
  text 'TO:', style: :bold, size: 18
  padded_text c['client_name']
  padded_text c['client_address']
  move_down 20

  # BILL
  table_top = cursor - 10
  bounding_box([0, table_top], width: 200) do
    text 'DESCRIPTION', style: :bold
    move_down 10
    text "#{c['service']} for #{date.to_fs(:month_name_year)}"
  end

  bounding_box([250, table_top], width: 100) do
    text 'DAYS', style: :bold
    move_down 10
    text total_days.to_s
  end

  bounding_box([350, table_top], width: 100) do
    text 'RATE', style: :bold
    move_down 10
    text currency(c['rate'])
  end

  bounding_box([450, table_top], width: 90) do
    text 'AMOUNT', style: :bold, align: :right
    move_down 10
    text currency(c['rate'] * total_days), align: :right
  end

  move_up 30
  transparent(0.5) { stroke_horizontal_rule }
  move_down 200
  transparent(0.5) { stroke_horizontal_rule }
  move_down 10

  total_cursor = cursor
  bounding_box([350, total_cursor], width: 95) do
    text 'VAT (20%)', style: :bold, align: :right
    text 'TOTAL', style: :bold, align: :right
  end

  subtotal = c['rate'] * total_days
  vat = subtotal * 0.2
  bounding_box([450, total_cursor], width: 90) do
    text currency(vat), align: :right
    text currency(subtotal + vat), align: :right
  end

  text 'Payment terms', style: :bold, size: 18
  padded_text "Please pay within #{c['payment_terms']} days"
  move_down 5
  padded_text "Name: <b>#{c['account_name']}</b>", inline_format: true
  padded_text "Sort code: <b>#{c['account_sortcode']}</b>", inline_format: true
  padded_text "Account no: <b>#{c['account_number']}</b>", inline_format: true
end
